name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - uses: ./.github/actions/setup-and-install-dep
        
    - name: Login to Nuxeo Docker Registry
      uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
      with:
        registry: docker-private.packages.nuxeo.com
        username: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
        password: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}
        
    - name: Pull Nuxeo Docker Image
      run: |
        docker pull docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
        
    - name: Run integration tests
      env:
        NUXEO_DOCKER_IMAGE: docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
      run: |
        uv run pytest tests/ -v --integration
