name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    
    - uses: ./.github/actions/setup-and-install-dep
        
    - name: Login to Nuxeo Docker Registry
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: docker-private.packages.nuxeo.com
        username: ${{ secrets.REPOSITORY_MANAGER_USERNAME }}
        password: ${{ secrets.REPOSITORY_MANAGER_PASSWORD }}
        
    - name: Pull Nuxeo Docker Image
      run: |
        docker pull docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
        
    - name: Run integration tests
      env:
        NUXEO_DOCKER_IMAGE: docker-private.packages.nuxeo.com/nuxeo/nuxeo:2025
      run: |
        uv run pytest tests/ -v --integration
