name: Update Python Version

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6am
  workflow_dispatch:

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@499eb5d58f3f82a4efa4eaedab26dbecff18328c # v18.15.1
      
      - name: Run Updatecli
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: updatecli --config .updatecli/updatecli.d ${{ github.event_name == 'schedule' && 'apply' || 'diff' }}
