name: Update Python Version

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6am
  workflow_dispatch:

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@a6a8be7429080c132815d0482a55ae4fd28f15ba # v18.7.0
      
      - name: Run Updatecli
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: updatecli --config .updatecli/updatecli.d ${{ github.event_name == 'schedule' && 'apply' || 'diff' }}
