name: Update Python Version

on:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday at 6am
  workflow_dispatch:

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Updatecli
        uses: Alfresco/alfresco-build-tools/.github/actions/setup-updatecli@1d45cf78775e35e499c9fc8df3a040bfa7a1d87b # v18.17.0
      
      - name: Run Updatecli
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: updatecli --config .updatecli/updatecli.d ${{ github.event_name == 'schedule' && 'apply' || 'diff' }}
